config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.error_notification %>
  <%= f.input :address %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Add", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

<ul>
  <h1>All out Flats (<%= @flats.length %>)</h1>
  <div class="card-container">
    <% @flats.each do |flat| %>
    <div class="card">
      <div class="card-content">
        <li class="name">
          <%= flat.name %>
        </li>
        <li class="address">
          <%= flat.address %>
        </li>
        <div class="info">
          <li class="guests">
            <i class="symbol fas fa-user"></i>
            <%= flat.number_of_guests %>
          </li>
          <i class="symbol fas fa-euro-sign"></i>
          <li class="price">
            <%= flat.price_per_night %>
          </li>
        </div>
      </div>
      <div class="card-footer">
        <li>
          <%= link_to 'More info', flat_path(flat) %>
          <%= link_to 'Edit', edit_flat_path(flat) %>
          <%= link_to 'Remove', flat_path(flat), method: :delete,
            data: { confirm: 'Are you sure?' } %>
        </li>
      </div>
    </div>
    <% end %>
  </div>
</ul>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div id="googleMap" style="width:100%;height:400px;"></div>


<div class="card-container">
  <div class="card">
    <div class="card-content">
      <li class="name">
        <%= @flat.name %>
      </li>
      <li class="address">
        <%= @flat.address %>
      </li>
      <li class="description">
        <%= @flat.description %>
      </li>
      <div class="info">
        <li class="guests">
          <i class="symbol fas fa-user"></i>
          <%= @flat.number_of_guests %>
        </li>
        <i class="symbol fas fa-euro-sign"></i>
        <li class="price">
          <%= @flat.price_per_night %>
        </li>
      </div>
    </div>
      <li>
        <%= link_to 'Home', flats_path %>
      </li>
    </div>
  </div>
</div>

<script>
  function myMap() {
var mapProp= {
    center:new google.maps.LatLng(51.508742,-0.120850),
    zoom:5,
};
var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
}

</script>

<script src="https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap
&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318
&markers=color:red%7Clabel:C%7C40.718217,-73.998284
&key=AIzaSyBuQpVSocdlNpXVeLqygZwi-INoz2014qk
&callback=myMap"></script>
<script type="../assets/javascripts/application"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>